### PR TITLE
MySQL 顺序Guid算法更新

### PR DESCRIPTION
**Pull request by yuzukwok**
不同数据库顺序guid要求不同

### CODE REVIEW

**Comment by caleblloyd** [comment]
Why use this over the existing [SequentialGuidValueGenerator.cs](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/ValueGeneration/SequentialGuidValueGenerator.cs) in upstream?

**Comment by caleblloyd** [comment]
Ok, makes sense if SQL Server is putting their sequential values at the end.  MySql needs them at the beginning.

Let me see if I can fix this up a little, add tests, and open a separate PR.

**Comment by yuzukwok** [comment]
thank you

**Comment by caleblloyd** [comment]
We'll need to take into account GUID format in [MySqlScopedTypeMapper.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlScopedTypeMapper.cs#L78-L85)

It could be either `CHAR(36)` or `BINARY(16)`.  Will need to write a method to convert Binary to Hex and add dashes if it is `CHAR(36)`

**Comment by caleblloyd** [comment]
Closing in favor of #260

**Pull request closed without merging**
