### PR TITLE
Upgrade to 2.1.0-preview1

### PR DESCRIPTION
**Pull request by caleblloyd**
- Upgrade EF Upstream to 2.1.0-preview1
- Currently WIP; do not merge

### CODE REVIEW

**Comment by rymnikski** [comment]
Hi there, when will be ready this release?

**Comment by caleblloyd** [comment]
No schedule as of now. Currently looking for help with blocking issues. See #514

**Comment by DSpade-r** [comment]
Is there any news about the release of the new version for Core 2.1? I wait when it is possible to do a selection from the views in the database.

**Comment by caleblloyd** [comment]
Work for 2.1.0 is now happening in `f_2.1.0-spec-tests` branch.

**Comment by rymnikski** [comment]
Is lazy loading working?

**Comment by caleblloyd** [comment]
> Is lazy loading working?

Not until `f_2.1.0-spec-tests` is merged and published.  Then it will work [as specified in the EF Core Docs](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading)

**Pull request closed without merging**
