### PR TITLE
Use Arcade for Build

### PR DESCRIPTION
**Pull request by caleblloyd**
.NET Core packages now use https://github.com/dotnet/arcade to build

Change build system to use arcade

### CODE REVIEW

**Comment by lauxjpn** [comment]
It would also be useful to have a couple of different database environments setup and tested against, like in the `.travis.yaml` from `MySqlConnector`:

https://github.com/mysql-net/MySqlConnector/blob/0259c09fdef5bd5bd7dbb70c91093c48a3063afc/.travis.yml#L5-L26

**Comment by caleblloyd** [comment]
Yes multiple DBs would be a good future addition, I think that's not too hard with the [matrix job strategy](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#matrix)

**Comment by lauxjpn** [comment]
Just an FYI:
The build paths have changed from their individual project directories to `/artifacts`.

**Comment by lauxjpn** [comment]
This also touched a lot of files unnecessarily without changing any content. Is this a BOM issue, that should be handled for the whole repo?

**Pull request merged**
