### PR TITLE
[WIP] Feature/netcore3.0

### PR DESCRIPTION
**Pull request by twsI**
This is the work in progress for the support of .NET Core 3.
There is still a lot to do: tests are not working yet, quite a lot of things are unclear to me and it might need a general cleanup. But a lot of API calls are updated already and I hope, that this work can contribute towards the next release somehow. I am unsure whether I can continue to work on this or not and I would love to see someone take over.

Further discussion can be found within this issue #797 

In case you'd like to thank me for my work, please like this issue https://github.com/aspnet/EntityFrameworkCore/issues/11597

### CODE REVIEW

**Comment by lauxjpn** [comment]
What is the branching strategy here? Should this be merged into a new `3.0` branch, or kept on `master` and later branched, when going GA?

**Comment by iHamzaKhanzada** [comment]
Can I have a rough estimate about when the support for netcore3.0 is rolling out?

**Comment by rusuly** [comment]
It seems the PR was't tested properly in runtime.
It throws exceptions when used with simple cases:

1)MySqlMigrationsSqlGenerator.ColumnDefinition throws NRE for string columns when generating database. I believe the corresponding `if` statement is missing in MySqlMigrationsAnnotationProvider for MySqlValueGenerationStrategy.None so it returns null.

2)MySqlCompiledQueryCacheKeyGenerator.Equals also generates NRE when comparing _nullableCharSetBehavior.Value. This happens when I perform a simple Where query

3)Also there is Int64 to Int32 conversion exception when EnsureCreatedAsync is called and the database exists

**Comment by twsI** [comment]
> 
> 
> Can I have a rough estimate about when the support for netcore3.0 is rolling out?

I can in no way provide an estimation, I just put in some time to migrate some API calls to give the migration to .NET Core 3 a headstart.

> 
> 
> It seems the PR was't tested properly in runtime.
> It throws exceptions when used with simple cases:
> 
> 1)MySqlMigrationsSqlGenerator.ColumnDefinition throws NRE for string columns when generating database. I believe the corresponding `if` statement is missing in MySqlMigrationsAnnotationProvider for MySqlValueGenerationStrategy.None so it returns null.
> 
> 2)MySqlCompiledQueryCacheKeyGenerator.Equals also generates NRE when comparing _nullableCharSetBehavior.Value. This happens when I perform a simple Where query
> 
> 3)Also there is Int64 to Int32 conversion exception when EnsureCreatedAsync is called and the database exists

As I already said and stated above: this is still a WIP and there is still a lot todo. I even mentioned the failed tests. Feel free to continue on my work, my knowledge regarding MySQL and EFCore is quite limited.

**Comment by lauxjpn** [comment]
I spend the weekend upgrading the provider to EfCore 2.2.6.
Right now, I am fixing as many tests as possible, so we will have a nice foundation to upgrade to 3.0 on.

**Comment by alxwest** [comment]
There's a few things I can contribute with here but I haven't got review access. I can do PR to your repo @twsI if that takes your fancy?

**Comment by twsI** [comment]
> 
> 
> There's a few things I can contribute with here but I haven't got review access. I can do PR to your repo @twsI if that takes your fancy?

Sure, feel free to do so.

**Comment by lauxjpn** [comment]
I am going to upload the upgrade to EFCore 2.2.6 and open a PR shortly (< 24h).
There are still tests that fail, but the test suit contains 2000 tests more in 2.2.6 then in 2.2.0, and they are very likely to test scenarios, that would have failed before, if those tests would have existed.

**Comment by caleblloyd** [comment]
@twsI thanks for the PR.  I do not currently have the time to dedicate to reviews/performing upgrades, I believe others in the community do though!  I created a new base branch `2.2.6-wip` and `3.0.0-wip` and gave you write access to them.  Let me know if any issues merging PRs into them.

I am happy to help with maintenance tasks such as merges to master and publishing releases once they are ready.

**Comment by lauxjpn** [comment]
Alright, based an the work of @twsI , I filled in the gaps and finished the primary update process for the provider.

The only thing I did not update yet (currently disabled by comment), is the `NO_BACKSLASH_ESCAPES` handling here:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3c01ad48f1dfa921a1a528e944a069ab2680d2a8/src/EFCore.MySql/Query/Sql/Internal/MySqlQuerySqlGenerator.cs#L129-L150

I will continue with the tests, so we can evaluate, what needs to be done.

**Comment by lauxjpn** [comment]
The 2.2.6 update #820 has been merged.
@twsI

**Comment by lauxjpn** [comment]
@iHamzaKhanzada There will be a 3.0 compatible version available in the next couple of days. This version will still be in development, but most features that did not depend on client evaluation before, should work just fine.

**Comment by lauxjpn** [comment]
@twsI You don't need to merge this PR anymore. I have based the 3.0 upgrade on your commits from your own repository and will open a separate PR with them shortly.

**Comment by twsI** [comment]
> 
> 
> @twsI You don't need to merge this PR anymore. I have based the 3.0 upgrade on your commits from your own repository and will open a separate PR with them shortly.

I appreciate that, thanks for your hard work so far!
I will close this issue as soon as you open your PR.

**Comment by lauxjpn** [comment]
The new PR will be up in a couple of hours. There are still a couple of error clusters present in the test suite, but most functionality should be up and running.

**Comment by twsI** [comment]
Therefore closing this due to the awesome work @lauxjpn provided in the referenced PR

**Pull request closed without merging**
