### PR TITLE
Support translate Guid.NewGuid() and Random.Next()

### PR DESCRIPTION
**Pull request by Kagamine**

### CODE REVIEW

**Comment by Kagamine** [comment]
@caleblloyd

**Comment by caleblloyd** [comment]
Hey @Kagamine I am slammed at work right now.  Can try to look over the weekend

**Comment by Kagamine** [comment]
Smart type mapper is a good thing for mapping with different versions of MySQL server, but It really against unit tests, so we should make a design for UT.

**Comment by caleblloyd** [comment]
Unit Tests should not connect to the database; I think these tests belong in the Functional Tests project

**Comment by Kagamine** [comment]
@caleblloyd Could you refactor this PR?

**Comment by caleblloyd** [comment]
I should be able to over the next couple days. I'll try to use an existing model to test it against so I can get it done quicker. Going to reopen to track it

**Comment by caleblloyd** [comment]
@Kagamine I couldn't figure out how to get `random.Next` or `random.NextDouble` working.  I spent a couple hours on it and had no luck.  I kept the `Guid.NewGuid` change but backed out the `random` change.

**Pull request merged**
