### PR TITLE
Enable source link support

### PR DESCRIPTION
**Pull request by lauxjpn**
The CI needs to be updated for that and we should discuss, how to ship the PDBs (keep them portable or embed them instead).

### CODE REVIEW

**Comment by lauxjpn** [comment]
@caleblloyd CI triggering stopped working about an hour ago. Is this a problem on our end or a service failure of AZDO?

**Comment by caleblloyd** [comment]
Not sure, what's your Microsoft account email I'll add you as an AZDO admin

**Comment by lauxjpn** [comment]
lau17ex add hotmail dodd comm

**Comment by caleblloyd** [comment]
Added

**Comment by lauxjpn** [comment]
Thanks!

**Comment by lauxjpn** [comment]
We will publish `snupkg` files with together with the `nupkg` files for NuGet.org. For AZDO (due to lack of `snupkg` support), we add PDB symbols to the symbol server.

**Pull request merged**
