### PR TITLE
Pr/schema support

### PR DESCRIPTION
**Pull request by pkiers**
Added support for schema, if I missed something or you want some tests just let me know and I will add them. Got everything already working for us in our production where we work with multiple schema´s.

### CODE REVIEW

**Comment by pkiers** [comment]
@caleblloyd I can work on that some later this week.

**Comment by xyting** [comment]
@pkiers I think the `MySqlQuerySqlGenerator.VisitTable(TableExpression)` need to sync change

**Comment by pkiers** [comment]
@xyting Where does it remove schema?

```
public override Expression VisitTable(TableExpression tableExpression)
{
    Check.NotNull(tableExpression, nameof(tableExpression));

    Sql.Append(SqlGenerator.DelimitIdentifier(tableExpression.Table, tableExpression.Schema))
        .Append(" AS ")
        .Append(SqlGenerator.DelimitIdentifier(tableExpression.Alias));

    return tableExpression;
}
```
The method uses `tableExpression.Schema` or am I missing something :)

**Comment by xyting** [comment]
@pkiers My fault, yes, this code is right.

**Pull request merged**
