### PR TITLE
Implement support for index/key prefix lengths

### LINKED ISSUE #936: Add `HasKeyLength` method (for indices/keys)
### Steps to reproduce
It's migration of tables for Identity.

```
>              /*migrationBuilder.AlterColumn<string>(
                name: "Id", <-- It's PrimaryKey!
                table: "AspNetUsers",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "varchar(255)");*/
> 
>             /*migrationBuilder.AlterColumn<string>(
>                 name: "LoginProvider", <-- It's Index!
>                 table: "AspNetUserTokens",
>                 nullable: false,
>                 oldClrType: typeof(string),
>                 oldType: "varchar(255)");*/
> 
>             /*migrationBuilder.AlterColumn<string>(
>                 name: "UserId", <-- It's ForeignKey!
>                 table: "AspNetUserTokens",
>                 nullable: false,
>                 oldClrType: typeof(string),
>                 oldType: "varchar(255)");*/
```

### The issue
**LongText can't be PrimaryKey, ForeignKey and Index!**

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)

### Further technical details

MySQL version: 8.0
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc3.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:

### PR DESCRIPTION
**Pull request by lauxjpn**
The following code can be used to specify prefix lengths for indices:

```c#
// One column:
entity.HasIndex(e => e.SingleProperty)
    .HasPrefixLength(48);

// Multiple columns:
entity.HasIndex(e => new { e.FirstProperty, e.SecondProperty })
    .HasPrefixLength(0, 32);
```

The code to specify prefix lengths for keys is similar:

```c#
// One column:
entity.HasKey(e => e.SingleProperty)
    .HasPrefixLength(48);

// Multiple columns:
entity.HasKey(e => new { e.FirstProperty, e.SecondProperty })
    .HasPrefixLength(0, 32);
```

If you want to specify the usage of the whole length of a column as part of an index/key, specify the length as `0`, as can be seen in the `Multiple columns` examples.

~~I am not sure, if we should use the singular `HasPrefixLength`, instead of the plural.~~

Closes #936 

Also addresses #872, #380, #298, #259, #136, #99, #81 and #7

### CODE REVIEW

**Comment by mguinness** [comment]
> I am not sure, if we should use the singular `HasPrefixLength`, instead of the plural.

I would go for singular as it's consistent with all the other method names.

**Comment by olicooper** [comment]
I opened an issue with EFCore team but they pointed me to you guys.. [original issue](https://github.com/dotnet/efcore/issues/20751#issuecomment-619364616)

Could you extend this to support `index` prefix lengths too? From the example above this is specific to keys only?

**Comment by olicooper** [comment]
Currently when creating an index, the migration builder converts string properties to `varchar(255)` when adding an index using the FluentAPI. Will we be able to use this new functionality without the builder converting `LONGTEXT` columns to `varchar(255)`?

**Comment by lauxjpn** [comment]
@olicooper Good point! We should remove the current behavior to limit the key, now that the prefix can be set. This was always more of a hack anyway. However, since this would be a breaking change, we will remove this only for the .NET/EF Core 5 release.

**Pull request merged**
