### PR TITLE
My attempt at adding idempotent migrations

### LINKED ISSUE #424: To support generate idempotent migration script
This is my error, or this version does not support publish migration
Error  Message: Generating idempotent scripts for migration is not currently supported by MySql
Trace:
```bigdog -> C:\Users\User\documents\visual studio 2017\Projects\bigdog\bigdog\obj\Release\netcoreapp2.0\PubTmp\Out\
Generating Entity framework SQL Scripts...
Executing command: dotnet ef migrations script --idempotent --output "C:\Users\User\documents\visual studio 2017\Projects\bigdog\bigdog\obj\Release\netcoreapp2.0\PubTmp\EFSQLScripts\bigdog.Data.ApplicationDbContext.sql" --context bigdog.Data.ApplicationDbContext 
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\User\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'ApplicationDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
System.NotSupportedException: Generating idempotent scripts for migration is not currently supported by MySql
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MySqlHistoryRepository.GetBeginIfNotExistsScript(String migrationId)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, Boolean idempotent)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Generating idempotent scripts for migration is not currently supported by MySql

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(93,5): Ошибка : Entity framework SQL Script generation failed```

### PR DESCRIPTION
**Pull request by Meberem**
Hopefully resolves #424

This seems to be the way to run conditional statements in MySql, I am not a daily user of MySql so if anyone has other ways of accomplishing it I would be keen to learn them.

### CODE REVIEW

**Comment by grapoza** [comment]
Looks like you beat me to it; I just committed a very similar implementation in https://github.com/grapoza/Pomelo.EntityFrameworkCore.MySql/commit/f105eaa117c715fc71b1468cd62f8e78d3b432c5 using the same script-around-migrations approach. It's heavy handed, but it works and it's the best I've found (though I'm also not a MySql guy).

**Comment by wiredbarb** [comment]
I tested this with a real-life project - the generated idempotent script successfully applies our migration changes to both MariaDB 10.2.16 and MySQL 8.0.12 database instances as well as for both empty and already migrated databases.

So +1 for getting this merged.

**Comment by wiredbarb** [comment]
@mguinness Do you see a need for further revision here?

**Comment by mguinness** [comment]
@caleblloyd @yukozh Can we give wiredbarb maintainer rights on the repo so he can merge changes?

**Comment by caleblloyd** [comment]
yes good idea, I invited you @wiredbarb 

I have not had time to do a deep-dive to review these changes, but if you are comfortable with them please do merge

**Pull request merged**
