### PR TITLE
Proposed fix for #1484

### PR DESCRIPTION
**Pull request by twsl**
Fix for #1484 proposed by @mguinness for an weird quirk in an old, unsupported version of MySql.

### CODE REVIEW

**Comment by mguinness** [comment]
Don't you have to make the same changes in `GetIndexes()`?

You'll have to wait for lauxjpn to take a look at the build errors which seem to be occuring in `MySqlJsonMicrosoftTypeMapping`.

**Comment by lauxjpn** [comment]
> I created a draft PR, but the tests fail and I cannot see the azure pipelines error.

You should be able to see them. They are public:

image

image

image

image

The pipeline fails because of some changes in the latest .NET preview, that leads to some ambiguities. This is unrelated to this issue here.
I will upload a fix for the pipeline issue, that then limits the .NET version to a specific one.

**Review by lauxjpn — DISMISSED** [review]
I think it is safe to just use `CAST()` for all versions.
Please add a test or two that would fail without your code fix.

**Comment by twsl** [comment]
Thanks for the extensive help, not sure why I wasn't able to see them previously; now I don't see the azure error I used to see before. I'll try to come up with tests asap.

**Comment by lauxjpn** [comment]
> Yet I fail to understand, why the pipeline fails, the error messages are not really helpful.

The pipeline is currently configured to use the latest preview of .NET 6. In the latest iteration, they have made some changes to the `Lazy<>` class that lead to some ambiguous calls where .NET cannot say with certainty anymore, what method (in this case constructor) was intended to be called.

I hit the same issue locally a couple of weeks ago when trying to compile Pomelo against the latest .NET preview.

**Comment by twsl** [comment]
> I think it is safe to just use `CAST()` for all versions.
> Please add a test or two that would fail without your code fix.

That would make the Version.Supports property useless and it can be safely removed, right?
And I am unsure how to structure a test and what to mock with the cast fix, as the specific MySql version simply returns a blob instead of a char inside the query. Can you provide some directions @lauxjpn ? Are tests even required?

**Comment by lauxjpn** [comment]
> Are tests even required?

I think it is probably enough to just add a test to `MySqlDatabaseModelFactoryTest`'s primary key facets and index facets region respectively, to demonstrate that the `CAST()` change does not break the execution of the query.
Just verify locally on your end that the test case fails with MySQL 5.1 without the fix, because we don't test MySQL 5.1 in CI.

> That would make the Version.Supports property useless and there is no need for it, right?

Yes, I don't think we need it.

---

It is possible to use Moq or manually mock it in a way, that you change the return type to `byte[]` instead of `string` for `SUB_PARTS`, but that is probably overkill as we want to keep this fix as simple as possible.

**Comment by twsl** [comment]
I don't think that additional tests are required because both functions are called every time a test database is initialized within the existing tests. If they don't fail, everything should be fine.
Due to errors with c#10 language features in VS and/or the already mentioned lazy build errors I cannot properly test everything.

**Comment by lauxjpn** [comment]
> Due to errors with c#10 language features in VS and/or the already mentioned lazy build errors I cannot properly test everything.

Even with those fixed, the tests will not run against MySQL 5.1, because they use features like the `utf8mb4` charset, that were not supported back then.

Just rebase your PR on top of the latest commit, which fixes the `Lazy<>` issue, so the CI succeeds.
We'll merge it then.

**Comment by twsl** [comment]
@lauxjpn can I click the merge button myself? I always forget that someone once made me a team member 😄

**Pull request merged**
