### PR TITLE
Fixes default value scaffolding bug

### LINKED ISSUE #347: Columns with default value of empty string do not scaffold correctly
### Steps to reproduce
1. Create a table as follows:

```
CREATE TABLE `Batch` (
    `BatchID` int(10) unsigned NOT NULL DEFAULT 0,
    `Allocation` varchar(100) NOT NULL DEFAULT "",
    `BatchName` varchar(100) NOT NULL,
    CONSTRAINT `PK_batch` PRIMARY KEY (`BatchID`)
);

```

Run Scaffolding:

`Scaffold-DbContext –Connection “server=127.0.0.1;userid=me;pwd=mypassword;database=mydb;” -Provider Pomelo.EntityFrameworkCore.MySql –Context MyDbContext –Tables “Batch”`

### The issue
Resulting configuration misses off HasDefaultValue("") from the entity. Therefore, any use of 'EnsureCreated' will result in no default value for this field. This was working in previous releases. 
```

modelBuilder.Entity<Batch>(entity =>
            {
                entity.HasKey(e => e.BatchId)
                    .HasName("PK_Batch");

                entity.ToTable("Batch");

                entity.Property(e => e.BatchId)
                    .HasColumnName("BatchID")
                    .HasColumnType("int(10) unsigned")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Allocation)
                    .IsRequired()
                    .HasColumnType("varchar(100)");

                entity.Property(e => e.BatchName)
                    .IsRequired()
                    .HasColumnType("varchar(100)");
            });

```

### Further technical details

MySQL version: 5.7.18
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

### PR DESCRIPTION
**Pull request by Kagamine**
Fixes #347

### CODE REVIEW

**Comment by Kagamine** [comment]
@caleblloyd We should add test cases for scaffolding the fields which have default values.

**Comment by Kagamine** [comment]
@bgrainger Hi, I assume I've opened issue on MySqlConnector repo for requesting implement MySqlCommandBuilder. Not only the Pomelo.EFCore.MySql requires this feature, but also Azure Database for MySQL team. I hope this could be implemented soon, thx.

**Comment by bgrainger** [comment]
The MySqlCommandBuilder issue is mysql-net/MySqlConnector#303.

**Comment by bgrainger** [comment]
`MySqlCommandBuilder` is implemented in [MySqlConnector 0.34.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.34.0).

**Pull request merged**
