### PR TITLE
Add support for `string.IndexOf(string value, int startIndex) `

### PR DESCRIPTION
**Pull request by LeaFrock**
Fix issue #1625

### CODE REVIEW

**Comment by mguinness** [comment]
Can you add some functional tests, see [NorthwindFunctionsQueryMySqlTest](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.MySql.cs) class for examples.

**Comment by LeaFrock** [comment]
> Can you add some functional tests, see [NorthwindFunctionsQueryMySqlTest](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Query/NorthwindFunctionsQueryMySqlTest.MySql.cs) class for examples.

Of course. I'll handle it tomorrow, thanks.

**Comment by LeaFrock** [comment]
Functional tests added. @mguinness 
There seems to be a mistake for these two test methods, `StringIndexOf_invariant` & `StringIndexOf_current`.



If you're sure that it's a typo, I'll add a separate commit for fix.

**Review by lauxjpn — CHANGES_REQUESTED** [review]
Looks good!

> There seems to be a mistake for these two test methods, `StringIndexOf_invariant` & `StringIndexOf_current`.

Yes, please go ahead and just add another commit fixing those.

I'll fix the CI error regarding the Windows environment job, which is unrelated to your changes.

**Review by lauxjpn — APPROVED** [review]

**Comment by lauxjpn** [comment]
The Windows CI pipeline is fixed now.

@LeaFrock Please rebase your commits on top of the latest `master` commit and (force) push again.

The checks should succeed then and we will be able to merge your PR.

**Comment by LeaFrock** [comment]
@lauxjpn Done.

**Comment by lauxjpn** [comment]
@LeaFrock Thank you for your contribution!

**Pull request merged**
