### PR TITLE
Code Cleanup and Refactoring!

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
*Part 1 to initialize portability for 2.1-Preview1

### CODE REVIEW

**Comment by caleblloyd** [comment]
@ralmsdeveloper thanks for opening this. In general looks good, could you fix the failing unit tests though?

**Comment by ralmsdeveloper** [comment]
Yes of course!

**Comment by ralmsdeveloper** [comment]
@caleblloyd, done!
But now there is a problem on the server, this problem is not related to PR.

After merging this PR, I'd be happy to help you build the tests and use them in EFCore as a base (SQLServer)

**Comment by caleblloyd** [comment]
yes, there is an issue with the Appveyor test right now, I will work on fixing that soon

the Travis CI test works, it looks like there is just 1 failing test with some spaces that were changed around.  can you fix those:

https://travis-ci.org/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/builds/348507461?utm_source=github_status

I can merge once Travis passes, Appveyor runs a subset of Travis tests.

**Comment by ralmsdeveloper** [comment]
@caleblloyd  
That already works!
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/493/commits/9b045e5581f475fbc1e45101972220320d3740b7

**Comment by caleblloyd** [comment]
@ralmsdeveloper thanks, still looks like a test is failing but I'll merge and then get that fixed.

**Pull request merged**
