### PR TITLE
Implement Spatial support via NetTopologySuite (NTS)

### LINKED ISSUE #338: Scaffold fulltext index and spatial index

### LINKED ISSUE #488: Support for spatial data with MySQL?
### Steps to reproduce

``
dotnet ef dbcontext scaffold "server=xxx;port=3306;database=test;user id=xxx;password=xxx;sslmode=none" "Pomelo.EntityFrameworkCore.MySql" -o Model -c "Db" --verbose
``

### Target Framework

``
netcoreapp2.0
``

### The issue
No mapping column for mysql geometry type.

### Project configuration

``
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Telegram.Bot" Version="14.0.0-rc-367" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
</Project>
``

### Exceptions

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.13
dotnet exec --depsfile C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\bin\Debug\netcoreapp2.0\CatchMe.Telegram.deps.json --additionalprobingpath C:\Users\hanc\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\bin\Debug\netcoreapp2.0\CatchMe.Telegram.runtimeconfig.json "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools.dotnet\2.0.1\tools\netcoreapp2.0\ef.dll" dbcontext scaffold "server=xxxx;port=3306;database=test;user id=xxx;password=xxx;sslmode=none" Pomelo.EntityFrameworkCore.MySql -o Model -c Db --assembly C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\bin\Debug\netcoreapp2.0\CatchMe.Telegram.dll --startup-assembly C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\bin\Debug\netcoreapp2.0\CatchMe.Telegram.dll --project-dir C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\ --verbose --root-namespace CatchMe.Telegram
Using assembly 'CatchMe.Telegram'.
Using startup assembly 'CatchMe.Telegram'.
Using application base 'C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\bin\Debug\netcoreapp2.0'.
Using working directory 'C:\Users\hanc\Documents\VSCodes\Catchme.Telegram'.
Using root namespace 'CatchMe.Telegram'.
Using project directory 'C:\Users\hanc\Documents\VSCodes\Catchme.Telegram\'.
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
Using design-time services from provider 'Pomelo.EntityFrameworkCore.MySql'.
Finding IDesignTimeServices implementations in assembly 'CatchMe.Telegram'...
No design-time services were found.
column.

Could not find type mapping for column 'boundary.area' with data type 'geometry'. Skipping
```

### Further technical details

MySQL version: 5.7.20
Operating system: Ubuntu Server 17.10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:

### PR DESCRIPTION
**Pull request by lauxjpn**
This PR implements the long awaited spatial support.

~~Currently, 24/144 (MySQL) and 27/144 (MariaDB) tests don't run yet. I don't expect any serious issues there, just some unsupported or differently implemented functions on the database side. I will check them one by one over the next 48 hours or so.~~

~~We still need to add an extension method, to (optionally) restrict a column to a specific SRID and scaffold spatial indices (see #338)~~.

Anyone should already feel free to try this PR before it is merged (@YYCMZERO)~~, but should be aware, that it depends on (is blocked by) https://github.com/mysql-net/MySqlConnector/pull/829~~.

~~Merging is currently **blocked** by https://github.com/mysql-net/MySqlConnector/issues/832, which lets some (spatial unrelated) tests fail.~~

Here a quick example how to use it:

<details>
<summary>Sample code</summary>

```c#
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NetTopologySuite.Geometries;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        public Geometry Area { get; set; }
        public Point Location { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=Spatial00",
                    b => b
                        .ServerVersion("8.0.20-mysql")
                        .UseNetTopologySuite())
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasIndex(e => e.Location)
                        .IsSpatial();
                    
                    // MySQL can only use a spatial index, if the column is NOT NULL.
                    entity.Property(e => e.Location)
                        .IsRequired();
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            // POINT(1 2)
            var point = new Point(1.0, 2.0);
            
            // POLYGON((0 0,1 0,0 1,0 0))
            var polygon = new Polygon(new LinearRing(new[] {new Coordinate(0, 0), new Coordinate(1, 0), new Coordinate(0, 1), new Coordinate(0, 0)}));

            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.IceCreams.AddRange(
                    new IceCream
                    {
                        Name = "Vanilla",
                        Area = point,
                        Location = point,
                    },
                    new IceCream
                    {
                        Name = "Vanilla",
                        Area = polygon,
                        Location = point,
                    });
                
                context.SaveChanges();
            }

            using (var context = new Context())
            {
                var iceCreams = context.IceCreams
                    .OrderBy(i => i.IceCreamId)
                    .ToList();
                
                Debug.Assert(iceCreams.Count == 2);
                Debug.Assert(iceCreams[0].Area.EqualsExact(point));
                Debug.Assert(iceCreams[1].Area.EqualsExact(polygon));

                var iceCreamPoints = context.IceCreams
                    .Where(i => i.Location.X == 1.0)
                    .ToList();
                
                Debug.Assert(iceCreamPoints.Count == 2);
                Debug.Assert(iceCreamPoints[0].Location.Y == 2.0);
                Debug.Assert(iceCreamPoints[1].Location.Y == 2.0);
            }
        }
    }
}
```

</details>

<details>
<summary>Sample output</summary>

```c#
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.3 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.20 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled using NetTopologySuite

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (65ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP DATABASE `Spatial00`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Spatial00`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (82ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `IceCreams` (
          `IceCreamId` int NOT NULL AUTO_INCREMENT,
          `Name` longtext CHARACTER SET utf8mb4 NULL,
          `Area` geometry NULL,
          `Location` geometry NOT NULL,
          CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (123ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE SPATIAL INDEX `IX_IceCreams_Location` ON `IceCreams` (`Location`);

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (24ms) [Parameters=[@p0='0x000000000101000000000000000000F03F0000000000000040' (DbType = Binary), @p1='0x000000000101000000000000000000F03F0000000000000040' (Nullable = false) (DbType = Binary), @p2='Vanilla' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `IceCreams` (`Area`, `Location`, `Name`)
      VALUES (@p0, @p1, @p2);
      SELECT `IceCreamId`
      FROM `IceCreams`
      WHERE ROW_COUNT() = 1 AND `IceCreamId` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@p0='0x0000000001030000000100000004000000000000000000000000000000000000...' (DbType = Binary), @p1='0x000000000101000000000000000000F03F0000000000000040' (Nullable = false) (DbType = Binary), @p2='Vanilla' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `IceCreams` (`Area`, `Location`, `Name`)
      VALUES (@p0, @p1, @p2);
      SELECT `IceCreamId`
      FROM `IceCreams`
      WHERE ROW_COUNT() = 1 AND `IceCreamId` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.3 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.20 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled using NetTopologySuite

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `i`.`IceCreamId`, `i`.`Area`, `i`.`Location`, `i`.`Name`
      FROM `IceCreams` AS `i`
      ORDER BY `i`.`IceCreamId`

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `i`.`IceCreamId`, `i`.`Area`, `i`.`Location`, `i`.`Name`
      FROM `IceCreams` AS `i`
      WHERE ST_X(`i`.`Location`) = 1.0
```

</details>

Addresses #1033, https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/978#issuecomment-624199341
Closes #488
Closes #338

### CODE REVIEW

**Comment by yasir095** [comment]
I'm new so might be stupid question. I'm getting this:

The EF Core tools version '3.1.4' is older than that of the runtime '3.1.5'. Update the tools for the latest features and bug fixes.
**Could not find type mapping for column 'MerchantStoresCountry.lngLat' with data type 'point'. Skipping column.**

**When I run command:**
 dotnet ef dbcontext scaffold "server=myserver.rds.amazonaws.com;port=3306;user=admin;password=pwd;database=oauth;TreatTinyAsBoolean=true;" "Pomelo.EntityFrameworkCore.MySql" -o Models -f

Package im using is this added in .csproj and is installed
`<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.0-preview.20311.1" />`

**Startup.cs** 
```
services.AddDbContextPool<oauthContext>(options => options
                // replace with your connection string
                .UseMySql(Configuration.GetConnectionString("DefaultConnection"), mySqlOptions => mySqlOptions
                    // replace with your Server Version and Type
                    .ServerVersion(new Version(5, 7, 26), ServerType.MySql)
            ));
```

I have also tried adding and using  .UseNetTopologySuite() as in example:
  .ServerVersion(new Version(5, 7, 26), ServerType.MySql).UseNetTopologySuite() 
but i get error: 
                   

> MySqlDbContextOptionsBuilder' does not contain a definition for 'UseNetTopologySuite' and no accessible extension method 'UseNetTopologySuite' accepting a first argument of type 'MySqlDbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by lauxjpn** [comment]
@yasir095 You need to add the use the `Pomelo.EntityFrameworkCore.MySql` and `Pomelo.EntityFrameworkCore.MySql.NetTopologySuite` packages.

Currently, there has not been an official release of them to nuget.org yet, so you must use our [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds). Because these are not yet in an official release, you need to enable prereleases/previews.

The current version is `3.2.0-preview.20313.3`, which is the first version that contains the NTS package. The `3.2.0-preview.20311.1` you are using does not yet contain the NTS package.

After you are using the correct version, `.UseNetTopologySuite()` will be available. To query a point (x and y coordinates) from a `geometry` table column, you need to use the `Point` type from the `NetTopologySuite` package.

**Comment by yasir095** [comment]
Thanks manage to add it. Doesn't generate model automatically but I guess that will be once it's released officially.

**Comment by lauxjpn** [comment]
> Doesn't generate some parts of model automatically [...]

@yasir095 Do you mean it is not scaffolding everything correctly? If so, please post the `CREATE TABLE` statements and the incomplete model classes that got generated (or explain, what is missing), so we can take a look at it and fix it, before we release the spatial support in `3.2.0`.

**Comment by yasir095** [comment]
I'll post that today.

**Comment by yasir095** [comment]
Using DB first Approach: (Mysql version: 5.7.26 , .NetCore: 3.1)
OS X: 10.14.6 , VS: 8.6.3(30)

**.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.0-preview.20313.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.NetTopologySuite" Version="3.2.0-preview.20313.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**SQL**: 
`CREATE SCHEMA IF NOT EXISTS `TestDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `TestDB` ;

CREATE TABLE IF NOT EXISTS `TestDB`.`Location` (
  `name` VARCHAR(155) NOT NULL,
  `lngLat` POINT NOT NULL,
  PRIMARY KEY (`name`),
  SPATIAL INDEX `sp_index` (`lngLat`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
`
**Scaffolding Command**

> dotnet ef dbcontext scaffold "server=db1.myurl.amazonaws.com;Database=TestDB;Port=3306;User=admin;password=mypassword;TreatTinyAsBoolean=true;" "Pomelo.EntityFrameworkCore.MySql" -o Models

**Response:**

> Could not find type mapping for column 'Location.lngLat' with data type 'point'. Skipping column.
> Unable to scaffold the index 'sp_index'. The following columns could not be scaffolded: lngLat.

**Generated Models:**

```
namespace TestSpatialDataSupport.Models
{
    public partial class Location
    {
        public string Name { get; set; }
    }
}
```

```
namespace TestSpatialDataSupport.Models
{
    public partial class TestDBContext : DbContext
    {
        public TestDBContext()
        {
        }

        public TestDBContext(DbContextOptions<TestDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Location> Location { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            	optionsBuilder.UseMySql("server=db1.myurl.amazonaws.com;Database=TestDB;Port=3306;User=admin;password=mypassword;TreatTinyAsBoolean=true;", x => x.ServerVersion("5.7.26-mysql"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Location>(entity =>
            {
                entity.HasKey(e => e.Name)
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0 });

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasColumnType("varchar(155)")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_general_ci");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

**Comment by lauxjpn** [comment]
We have only mapped the `geometry` type yet (that does allow to use all derived types like `point`). But I will add the missing rest of the spatial type hierarchy later today.

**Comment by lauxjpn** [comment]
> I will add the missing rest of the spatial type hierarchy later today.

This has been implemented in #1105.

To effectively use scaffolding and spatial types together, you have to make sure, that the spatial support related services from the NTS package have been registered before the scaffolder runs.

The simplest way to do this, is to add the following class to your project (the class name is arbitrary):

```c#
public class EFCoreDesignTimeService : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
        => serviceCollection.AddEntityFrameworkMySqlNetTopologySuite();
}
```

**Comment by yasir095** [comment]
Thanks, it worked by adding the class you mentioned.

**Comment by surenatoyan** [comment]
> @yasir095 You need to use both, the `Pomelo.EntityFrameworkCore.MySql` and `Pomelo.EntityFrameworkCore.MySql.NetTopologySuite` packages.
> 
> Currently, there has not been an official release of them to nuget.org yet, so you must use our [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds). Because these are not yet in an official release, you need to enable prereleases/previews.
> 
> The current version is `3.2.0-preview.20313.3`, which is the first version that contains the NTS package. The `3.2.0-preview.20311.1` version you are using, does not yet contain the NTS package.
> 
> After you are using the correct version, `.UseNetTopologySuite()` will be available. To query a point (x and y coordinates) from a `geometry` table column, you need to use the `Point` type from the `NetTopologySuite` package (see my sample code above).

Hi,

How to find 3.2.0-preview.20313.3 versions for Pomelo.EntityFrameworkCore.MySql and Pomelo.EntityFrameworkCore.MySql.NetTopologySuite? The latest version is 3.1.1 on NuGet.

Regards.

**Comment by lauxjpn** [comment]
@surenatoyan As the text you quoted already states:

> Currently, there has not been an official release of them to nuget.org yet, **so you must use our [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds)**. Because these are not yet in an official release, you need to enable prereleases/previews.

You don't have to explicitly use `3.2.0-preview.20313.3`. Instead, use the newest version the nightly build feed provides.

**Pull request merged**
