### PR TITLE
Added support for database schema

### PR DESCRIPTION
**Pull request by pkiers**
Added support for database schema when using this in your dbcontext.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Account>(e => { e.ToTable("accounts", "accounts"); });

    base.OnModelCreating(modelBuilder);
}
```

### CODE REVIEW

**Comment by caleblloyd** [comment]
Adding support for `schema` will need tests.  Here's a quick list of operations that I can think that need to be tested:

- Migrations
- Insert/Update Operations
- Query Operations

**Comment by pkiers** [comment]
@caleblloyd Are you going to extend those tests or need I to add those in my pull request?

**Comment by caleblloyd** [comment]
@pkiers I have time to look at it this week unless you want to take a shot at it.

**Comment by pkiers** [comment]
@caleblloyd The function SqlGenerator.DelimitIdentifier("table" , "schema") returns "`schema`.`table`" while SqlGenerator.DelimitIdentifier("table" , null) returns "`table`".
The last one with the null is when you don't specify a schema in the ToTable method. So technically nothing could break.

That said, I will add / change some tests tomorrow and add them to the pull request.

**Comment by Kagamine** [comment]
You also should add schema logics into Migration Generator.

**Comment by pkiers** [comment]
@Kagamine @caleblloyd Just an update, am working on it in a new branch, updated the current migrations but still have to add some new tests for schema. Will do new pull request and close this one once I think it is all done. Lot of places there was already properly schemas being passed.

https://github.com/pkiers/Pomelo.EntityFrameworkCore.MySql/commit/ad672235ccb431b4d882188e740a1a8812aa2d30

**Comment by pkiers** [comment]
@Kagamine How do I get migrations working? I have tried a lot now not don't get anything really up and running.

**Comment by Kagamine** [comment]
I will reply to you later.

**Comment by pkiers** [comment]
@Kagamine If you see my commit (https://github.com/pkiers/Pomelo.EntityFrameworkCore.MySql/commit/ad672235ccb431b4d882188e740a1a8812aa2d30) you see that I have changed all that code already, but I wanted to try out the migrations in but I have issues running "dotnet ef Update-Database" and such. How does that work with Pomelo?

**Comment by caleblloyd** [comment]
It should be:

```
dotnet ef migrations add <name>
dotnet ef database update
```

Don't forget to [include tooling](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/project.json#L33)

**Comment by Kagamine** [comment]
I've commented on https://github.com/pkiers/Pomelo.EntityFrameworkCore.MySql/commit/ad672235ccb431b4d882188e740a1a8812aa2d30

**Comment by pkiers** [comment]
Sorry, been away and really busy but finishing up this today, closing this one PR because have other branch that I will add PR from when completed.

**Pull request closed without merging**
