### PR TITLE
Sequential GUIDs

### PR DESCRIPTION
**Pull request by caleblloyd**
- Adapt Sequential GUID generation to work on MySQL
- Re-work of initial PR #258 
- Must take into consideration if GUIDs are stored as `binary` (`OldGuids=true`) or `char(36)` (`OldGuids`=false)

Still need to add tests before we can merge

### CODE REVIEW

**Comment by jp7677** [comment]
Interesting.. What would I have to do to make advantage of this? We already use `char(36)` as column type for our GUIDs. Would this affect existing data?

**Comment by caleblloyd** [comment]
This only affects GUIDs that are part of the primary key that have not been set. It will set them automatically, no data annotation needed.

This happens right now, except the generated GUID is optimized for SQL Server, and not MySQL.

**Comment by jp7677** [comment]
Thanks for the info and nice improvement!

**Comment by caleblloyd** [comment]
@Kagamine tests are done for this, it's ready for review

**Comment by jp7677** [comment]
@Kagamine, Nice to see that this one has been merged. May I ask for a new nuget beta build, would love to play with it?

**Comment by Kagamine** [comment]
myget feed 1.1.2

**Comment by jp7677** [comment]
Thanks, that will do.

**Comment by Kagamine** [comment]
@caleblloyd Please revert this, I got a duplicate GUID in a concurrency scene.

**Comment by caleblloyd** [comment]
How long is your field? Are you truncating the random portion if the GUID?

This is a good addition, we should debug it not revert.

**Pull request merged**
