### PR TITLE
Fixes #327 mapping issue

### LINKED ISSUE #327: Invalid Default Value for Booleans
When trying to run a migration with a default value and a type of boolean, the generated SQL is 
```sql
ALTER TABLE `Configs` ADD `FarewellsEnabled` bit NOT NULL DEFAULT 'False';
```
Which is incorrect, manually running the SQL without the quotes around `False` successfully executes.

The same migration when downgraded to Pomelo.EntityFrameworkCore.MySql 1.1.2 runs perfectly fine.

The generated SQL for 1.1.2 is 
```sql
ALTER TABLE `Configs` ADD `FarewellsEnabled` bit NOT NULL DEFAULT FALSE;
```

### Further technical details

MySQL version: 5.7.13
Operating system: Windows 8.1
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-preview2-10046

### PR DESCRIPTION
**Pull request by Kagamine**
Fixes #327 
@caleblloyd There was a failed test case, could you help me take a look?

### CODE REVIEW

**Comment by caleblloyd** [comment]
I can look might need a day or two though

**Comment by Kagamine** [comment]
@caleblloyd It seems the smart type mapper does not work in UT, it always map DateTime into datetime(6)

**Comment by Kagamine** [comment]
Hi @caleblloyd, If you free, please take a look into this, In this PR contains bug fix for many types default value migration generating.

**Comment by caleblloyd** [comment]
Should be able to tomorrow or Monday at the latest!

**Comment by Kagamine** [comment]
Thanks

**Comment by caleblloyd** [comment]
@Kagamine MySQL 5.6 supports `datetime(6)` so I moved the 5.6 tests to mock 5.5 instead.  That way we can cover more edge cases in the same test class.

Also fixed it to mock `MySqlScopedTypeMapper` properly.

**Pull request merged**
